#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerModule
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PERSONNELMODULE")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPersonnels(Personnels instance);
    partial void UpdatePersonnels(Personnels instance);
    partial void DeletePersonnels(Personnels instance);
    partial void InsertDepartmans(Departmans instance);
    partial void UpdateDepartmans(Departmans instance);
    partial void DeleteDepartmans(Departmans instance);
    partial void InsertIzin(Izin instance);
    partial void UpdateIzin(Izin instance);
    partial void DeleteIzin(Izin instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::PerModule.Properties.Settings.Default.PerModuleCS, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Personnels> Personnels
		{
			get
			{
				return this.GetTable<Personnels>();
			}
		}
		
		public System.Data.Linq.Table<Departmans> Departmans
		{
			get
			{
				return this.GetTable<Departmans>();
			}
		}
		
		public System.Data.Linq.Table<Izin> Izin
		{
			get
			{
				return this.GetTable<Izin>();
			}
		}
		
		public System.Data.Linq.Table<Calendar> Calendar
		{
			get
			{
				return this.GetTable<Calendar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personnels")]
	public partial class Personnels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _PerTckn;
		
		private string _PerAd;
		
		private string _PerSoyad;
		
		private System.DateTime _PerDogumTarihi;
		
		private System.Nullable<int> _PerMaas;
		
		private string _PerCinsiyet;
		
		private string _PerMail;
		
		private string _PerTel;
		
		private string _PerGorsel;
		
		private System.Nullable<int> _PerEgitimBilgileri;
		
		private string _PerKanGrubu;
		
		private string _PerMedeniHali;
		
		private System.Nullable<int> _Adresid;
		
		private System.DateTime _PerBaslamaT;
		
		private System.Nullable<System.DateTime> _PerAyrilisT;
		
		private string _PerAyrilmaSebebi;
		
		private System.Nullable<int> _Departmanid;
		
		private string _PerNickName;
		
		private string _PerPassword;
		
		private string _PerYetki;
		
		private string _PerDogumYeri;
		
		private string _PerUyruk;
		
		private string _PerEhliyetS;
		
		private string _PerSicilNo;
		
		private System.Nullable<System.DateTime> _PerDEhliyetAlis;
		
		private string _PerSigaraK;
		
		private string _PerAskerlik;
		
		private string _PerIBAN;
		
		private System.Nullable<int> _Mesaiid;
		
		private string _PerIsTel;
		
		private string _PerWpTel;
		
		private string _Yakini1AdSoyad;
		
		private string _Yakini1Tel;
		
		private string _Yakini1Derece;
		
		private string _Yakini2AdSoyad;
		
		private string _Yakini2Tel;
		
		private string _Yakini2Derece;
		
		private string _SertifikaLisans1Ad;
		
		private string _SertifikaLisans1VerenKurum;
		
		private System.Nullable<System.DateTime> _SertifikaLisans1Tarihi;
		
		private string _SertifikaLisans2Ad;
		
		private string _SertifikaLisans2VerenKurum;
		
		private System.Nullable<System.DateTime> _SertifikaLisans2Tarihi;
		
		private string _YabanciDil1;
		
		private string _YabanciDil1Düzey;
		
		private string _YabanciDil2;
		
		private string _YabanciDil2Düzey;
		
		private string _YabanciDil3;
		
		private string _YabanciDil3Düzey;
		
		private string _IsYeri1;
		
		private string _IsUnvan1;
		
		private System.Nullable<System.DateTime> _IseGirisD1;
		
		private System.Nullable<System.DateTime> _IstenCikis1;
		
		private string _IstenAyrilis1;
		
		private string _IsYeri2;
		
		private string _IsUnvan2;
		
		private System.Nullable<System.DateTime> _IseGirisD2;
		
		private System.Nullable<System.DateTime> _IstenCikis2;
		
		private string _IstenAyrilis2;
		
		private string _IsYeri3;
		
		private string _IsUnvan3;
		
		private System.Nullable<System.DateTime> _IseGirisD3;
		
		private System.Nullable<System.DateTime> _IstenCikis3;
		
		private string _IstenAyrilis3;
		
		private string _IsYeri4;
		
		private string _IsUnvan4;
		
		private System.Nullable<System.DateTime> _IseGirisD4;
		
		private System.Nullable<System.DateTime> _IstenCikis4;
		
		private string _IstenAyrilis4;
		
		private System.Nullable<int> _Durum;
		
		private EntityRef<Departmans> _Departmans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnPerTcknChanging(string value);
    partial void OnPerTcknChanged();
    partial void OnPerAdChanging(string value);
    partial void OnPerAdChanged();
    partial void OnPerSoyadChanging(string value);
    partial void OnPerSoyadChanged();
    partial void OnPerDogumTarihiChanging(System.DateTime value);
    partial void OnPerDogumTarihiChanged();
    partial void OnPerMaasChanging(System.Nullable<int> value);
    partial void OnPerMaasChanged();
    partial void OnPerCinsiyetChanging(string value);
    partial void OnPerCinsiyetChanged();
    partial void OnPerMailChanging(string value);
    partial void OnPerMailChanged();
    partial void OnPerTelChanging(string value);
    partial void OnPerTelChanged();
    partial void OnPerGorselChanging(string value);
    partial void OnPerGorselChanged();
    partial void OnPerEgitimBilgileriChanging(System.Nullable<int> value);
    partial void OnPerEgitimBilgileriChanged();
    partial void OnPerKanGrubuChanging(string value);
    partial void OnPerKanGrubuChanged();
    partial void OnPerMedeniHaliChanging(string value);
    partial void OnPerMedeniHaliChanged();
    partial void OnAdresidChanging(System.Nullable<int> value);
    partial void OnAdresidChanged();
    partial void OnPerBaslamaTChanging(System.DateTime value);
    partial void OnPerBaslamaTChanged();
    partial void OnPerAyrilisTChanging(System.Nullable<System.DateTime> value);
    partial void OnPerAyrilisTChanged();
    partial void OnPerAyrilmaSebebiChanging(string value);
    partial void OnPerAyrilmaSebebiChanged();
    partial void OnDepartmanidChanging(System.Nullable<int> value);
    partial void OnDepartmanidChanged();
    partial void OnPerNickNameChanging(string value);
    partial void OnPerNickNameChanged();
    partial void OnPerPasswordChanging(string value);
    partial void OnPerPasswordChanged();
    partial void OnPerYetkiChanging(string value);
    partial void OnPerYetkiChanged();
    partial void OnPerDogumYeriChanging(string value);
    partial void OnPerDogumYeriChanged();
    partial void OnPerUyrukChanging(string value);
    partial void OnPerUyrukChanged();
    partial void OnPerEhliyetSChanging(string value);
    partial void OnPerEhliyetSChanged();
    partial void OnPerSicilNoChanging(string value);
    partial void OnPerSicilNoChanged();
    partial void OnPerDEhliyetAlisChanging(System.Nullable<System.DateTime> value);
    partial void OnPerDEhliyetAlisChanged();
    partial void OnPerSigaraKChanging(string value);
    partial void OnPerSigaraKChanged();
    partial void OnPerAskerlikChanging(string value);
    partial void OnPerAskerlikChanged();
    partial void OnPerIBANChanging(string value);
    partial void OnPerIBANChanged();
    partial void OnMesaiidChanging(System.Nullable<int> value);
    partial void OnMesaiidChanged();
    partial void OnPerIsTelChanging(string value);
    partial void OnPerIsTelChanged();
    partial void OnPerWpTelChanging(string value);
    partial void OnPerWpTelChanged();
    partial void OnYakini1AdSoyadChanging(string value);
    partial void OnYakini1AdSoyadChanged();
    partial void OnYakini1TelChanging(string value);
    partial void OnYakini1TelChanged();
    partial void OnYakini1DereceChanging(string value);
    partial void OnYakini1DereceChanged();
    partial void OnYakini2AdSoyadChanging(string value);
    partial void OnYakini2AdSoyadChanged();
    partial void OnYakini2TelChanging(string value);
    partial void OnYakini2TelChanged();
    partial void OnYakini2DereceChanging(string value);
    partial void OnYakini2DereceChanged();
    partial void OnSertifikaLisans1AdChanging(string value);
    partial void OnSertifikaLisans1AdChanged();
    partial void OnSertifikaLisans1VerenKurumChanging(string value);
    partial void OnSertifikaLisans1VerenKurumChanged();
    partial void OnSertifikaLisans1TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSertifikaLisans1TarihiChanged();
    partial void OnSertifikaLisans2AdChanging(string value);
    partial void OnSertifikaLisans2AdChanged();
    partial void OnSertifikaLisans2VerenKurumChanging(string value);
    partial void OnSertifikaLisans2VerenKurumChanged();
    partial void OnSertifikaLisans2TarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSertifikaLisans2TarihiChanged();
    partial void OnYabanciDil1Changing(string value);
    partial void OnYabanciDil1Changed();
    partial void OnYabanciDil1DüzeyChanging(string value);
    partial void OnYabanciDil1DüzeyChanged();
    partial void OnYabanciDil2Changing(string value);
    partial void OnYabanciDil2Changed();
    partial void OnYabanciDil2DüzeyChanging(string value);
    partial void OnYabanciDil2DüzeyChanged();
    partial void OnYabanciDil3Changing(string value);
    partial void OnYabanciDil3Changed();
    partial void OnYabanciDil3DüzeyChanging(string value);
    partial void OnYabanciDil3DüzeyChanged();
    partial void OnIsYeri1Changing(string value);
    partial void OnIsYeri1Changed();
    partial void OnIsUnvan1Changing(string value);
    partial void OnIsUnvan1Changed();
    partial void OnIseGirisD1Changing(System.Nullable<System.DateTime> value);
    partial void OnIseGirisD1Changed();
    partial void OnIstenCikis1Changing(System.Nullable<System.DateTime> value);
    partial void OnIstenCikis1Changed();
    partial void OnIstenAyrilis1Changing(string value);
    partial void OnIstenAyrilis1Changed();
    partial void OnIsYeri2Changing(string value);
    partial void OnIsYeri2Changed();
    partial void OnIsUnvan2Changing(string value);
    partial void OnIsUnvan2Changed();
    partial void OnIseGirisD2Changing(System.Nullable<System.DateTime> value);
    partial void OnIseGirisD2Changed();
    partial void OnIstenCikis2Changing(System.Nullable<System.DateTime> value);
    partial void OnIstenCikis2Changed();
    partial void OnIstenAyrilis2Changing(string value);
    partial void OnIstenAyrilis2Changed();
    partial void OnIsYeri3Changing(string value);
    partial void OnIsYeri3Changed();
    partial void OnIsUnvan3Changing(string value);
    partial void OnIsUnvan3Changed();
    partial void OnIseGirisD3Changing(System.Nullable<System.DateTime> value);
    partial void OnIseGirisD3Changed();
    partial void OnIstenCikis3Changing(System.Nullable<System.DateTime> value);
    partial void OnIstenCikis3Changed();
    partial void OnIstenAyrilis3Changing(string value);
    partial void OnIstenAyrilis3Changed();
    partial void OnIsYeri4Changing(string value);
    partial void OnIsYeri4Changed();
    partial void OnIsUnvan4Changing(string value);
    partial void OnIsUnvan4Changed();
    partial void OnIseGirisD4Changing(System.Nullable<System.DateTime> value);
    partial void OnIseGirisD4Changed();
    partial void OnIstenCikis4Changing(System.Nullable<System.DateTime> value);
    partial void OnIstenCikis4Changed();
    partial void OnIstenAyrilis4Changing(string value);
    partial void OnIstenAyrilis4Changed();
    partial void OnDurumChanging(System.Nullable<int> value);
    partial void OnDurumChanged();
    #endregion
		
		public Personnels()
		{
			this._Departmans = default(EntityRef<Departmans>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerTckn", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string PerTckn
		{
			get
			{
				return this._PerTckn;
			}
			set
			{
				if ((this._PerTckn != value))
				{
					this.OnPerTcknChanging(value);
					this.SendPropertyChanging();
					this._PerTckn = value;
					this.SendPropertyChanged("PerTckn");
					this.OnPerTcknChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PerAd
		{
			get
			{
				return this._PerAd;
			}
			set
			{
				if ((this._PerAd != value))
				{
					this.OnPerAdChanging(value);
					this.SendPropertyChanging();
					this._PerAd = value;
					this.SendPropertyChanged("PerAd");
					this.OnPerAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerSoyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PerSoyad
		{
			get
			{
				return this._PerSoyad;
			}
			set
			{
				if ((this._PerSoyad != value))
				{
					this.OnPerSoyadChanging(value);
					this.SendPropertyChanging();
					this._PerSoyad = value;
					this.SendPropertyChanged("PerSoyad");
					this.OnPerSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerDogumTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime PerDogumTarihi
		{
			get
			{
				return this._PerDogumTarihi;
			}
			set
			{
				if ((this._PerDogumTarihi != value))
				{
					this.OnPerDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._PerDogumTarihi = value;
					this.SendPropertyChanged("PerDogumTarihi");
					this.OnPerDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerMaas", DbType="Int")]
		public System.Nullable<int> PerMaas
		{
			get
			{
				return this._PerMaas;
			}
			set
			{
				if ((this._PerMaas != value))
				{
					this.OnPerMaasChanging(value);
					this.SendPropertyChanging();
					this._PerMaas = value;
					this.SendPropertyChanged("PerMaas");
					this.OnPerMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerCinsiyet", DbType="NVarChar(50)")]
		public string PerCinsiyet
		{
			get
			{
				return this._PerCinsiyet;
			}
			set
			{
				if ((this._PerCinsiyet != value))
				{
					this.OnPerCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._PerCinsiyet = value;
					this.SendPropertyChanged("PerCinsiyet");
					this.OnPerCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerMail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PerMail
		{
			get
			{
				return this._PerMail;
			}
			set
			{
				if ((this._PerMail != value))
				{
					this.OnPerMailChanging(value);
					this.SendPropertyChanging();
					this._PerMail = value;
					this.SendPropertyChanged("PerMail");
					this.OnPerMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerTel", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PerTel
		{
			get
			{
				return this._PerTel;
			}
			set
			{
				if ((this._PerTel != value))
				{
					this.OnPerTelChanging(value);
					this.SendPropertyChanging();
					this._PerTel = value;
					this.SendPropertyChanged("PerTel");
					this.OnPerTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerGorsel", DbType="NVarChar(300)")]
		public string PerGorsel
		{
			get
			{
				return this._PerGorsel;
			}
			set
			{
				if ((this._PerGorsel != value))
				{
					this.OnPerGorselChanging(value);
					this.SendPropertyChanging();
					this._PerGorsel = value;
					this.SendPropertyChanged("PerGorsel");
					this.OnPerGorselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerEgitimBilgileri", DbType="Int")]
		public System.Nullable<int> PerEgitimBilgileri
		{
			get
			{
				return this._PerEgitimBilgileri;
			}
			set
			{
				if ((this._PerEgitimBilgileri != value))
				{
					this.OnPerEgitimBilgileriChanging(value);
					this.SendPropertyChanging();
					this._PerEgitimBilgileri = value;
					this.SendPropertyChanged("PerEgitimBilgileri");
					this.OnPerEgitimBilgileriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerKanGrubu", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string PerKanGrubu
		{
			get
			{
				return this._PerKanGrubu;
			}
			set
			{
				if ((this._PerKanGrubu != value))
				{
					this.OnPerKanGrubuChanging(value);
					this.SendPropertyChanging();
					this._PerKanGrubu = value;
					this.SendPropertyChanged("PerKanGrubu");
					this.OnPerKanGrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerMedeniHali", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PerMedeniHali
		{
			get
			{
				return this._PerMedeniHali;
			}
			set
			{
				if ((this._PerMedeniHali != value))
				{
					this.OnPerMedeniHaliChanging(value);
					this.SendPropertyChanging();
					this._PerMedeniHali = value;
					this.SendPropertyChanged("PerMedeniHali");
					this.OnPerMedeniHaliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresid", DbType="Int")]
		public System.Nullable<int> Adresid
		{
			get
			{
				return this._Adresid;
			}
			set
			{
				if ((this._Adresid != value))
				{
					this.OnAdresidChanging(value);
					this.SendPropertyChanging();
					this._Adresid = value;
					this.SendPropertyChanged("Adresid");
					this.OnAdresidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerBaslamaT", DbType="DateTime NOT NULL")]
		public System.DateTime PerBaslamaT
		{
			get
			{
				return this._PerBaslamaT;
			}
			set
			{
				if ((this._PerBaslamaT != value))
				{
					this.OnPerBaslamaTChanging(value);
					this.SendPropertyChanging();
					this._PerBaslamaT = value;
					this.SendPropertyChanged("PerBaslamaT");
					this.OnPerBaslamaTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerAyrilisT", DbType="DateTime")]
		public System.Nullable<System.DateTime> PerAyrilisT
		{
			get
			{
				return this._PerAyrilisT;
			}
			set
			{
				if ((this._PerAyrilisT != value))
				{
					this.OnPerAyrilisTChanging(value);
					this.SendPropertyChanging();
					this._PerAyrilisT = value;
					this.SendPropertyChanged("PerAyrilisT");
					this.OnPerAyrilisTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerAyrilmaSebebi", DbType="NVarChar(150)")]
		public string PerAyrilmaSebebi
		{
			get
			{
				return this._PerAyrilmaSebebi;
			}
			set
			{
				if ((this._PerAyrilmaSebebi != value))
				{
					this.OnPerAyrilmaSebebiChanging(value);
					this.SendPropertyChanging();
					this._PerAyrilmaSebebi = value;
					this.SendPropertyChanged("PerAyrilmaSebebi");
					this.OnPerAyrilmaSebebiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departmanid", DbType="Int")]
		public System.Nullable<int> Departmanid
		{
			get
			{
				return this._Departmanid;
			}
			set
			{
				if ((this._Departmanid != value))
				{
					if (this._Departmans.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDepartmanidChanging(value);
					this.SendPropertyChanging();
					this._Departmanid = value;
					this.SendPropertyChanged("Departmanid");
					this.OnDepartmanidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerNickName", DbType="NVarChar(50)")]
		public string PerNickName
		{
			get
			{
				return this._PerNickName;
			}
			set
			{
				if ((this._PerNickName != value))
				{
					this.OnPerNickNameChanging(value);
					this.SendPropertyChanging();
					this._PerNickName = value;
					this.SendPropertyChanged("PerNickName");
					this.OnPerNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerPassword", DbType="NVarChar(8)")]
		public string PerPassword
		{
			get
			{
				return this._PerPassword;
			}
			set
			{
				if ((this._PerPassword != value))
				{
					this.OnPerPasswordChanging(value);
					this.SendPropertyChanging();
					this._PerPassword = value;
					this.SendPropertyChanged("PerPassword");
					this.OnPerPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerYetki", DbType="NVarChar(10)")]
		public string PerYetki
		{
			get
			{
				return this._PerYetki;
			}
			set
			{
				if ((this._PerYetki != value))
				{
					this.OnPerYetkiChanging(value);
					this.SendPropertyChanging();
					this._PerYetki = value;
					this.SendPropertyChanged("PerYetki");
					this.OnPerYetkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerDogumYeri", DbType="NVarChar(100)")]
		public string PerDogumYeri
		{
			get
			{
				return this._PerDogumYeri;
			}
			set
			{
				if ((this._PerDogumYeri != value))
				{
					this.OnPerDogumYeriChanging(value);
					this.SendPropertyChanging();
					this._PerDogumYeri = value;
					this.SendPropertyChanged("PerDogumYeri");
					this.OnPerDogumYeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerUyruk", DbType="NVarChar(50)")]
		public string PerUyruk
		{
			get
			{
				return this._PerUyruk;
			}
			set
			{
				if ((this._PerUyruk != value))
				{
					this.OnPerUyrukChanging(value);
					this.SendPropertyChanging();
					this._PerUyruk = value;
					this.SendPropertyChanged("PerUyruk");
					this.OnPerUyrukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerEhliyetS", DbType="NVarChar(3)")]
		public string PerEhliyetS
		{
			get
			{
				return this._PerEhliyetS;
			}
			set
			{
				if ((this._PerEhliyetS != value))
				{
					this.OnPerEhliyetSChanging(value);
					this.SendPropertyChanging();
					this._PerEhliyetS = value;
					this.SendPropertyChanged("PerEhliyetS");
					this.OnPerEhliyetSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerSicilNo", DbType="NVarChar(26)")]
		public string PerSicilNo
		{
			get
			{
				return this._PerSicilNo;
			}
			set
			{
				if ((this._PerSicilNo != value))
				{
					this.OnPerSicilNoChanging(value);
					this.SendPropertyChanging();
					this._PerSicilNo = value;
					this.SendPropertyChanged("PerSicilNo");
					this.OnPerSicilNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerDEhliyetAlis", DbType="DateTime")]
		public System.Nullable<System.DateTime> PerDEhliyetAlis
		{
			get
			{
				return this._PerDEhliyetAlis;
			}
			set
			{
				if ((this._PerDEhliyetAlis != value))
				{
					this.OnPerDEhliyetAlisChanging(value);
					this.SendPropertyChanging();
					this._PerDEhliyetAlis = value;
					this.SendPropertyChanged("PerDEhliyetAlis");
					this.OnPerDEhliyetAlisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerSigaraK", DbType="NVarChar(20)")]
		public string PerSigaraK
		{
			get
			{
				return this._PerSigaraK;
			}
			set
			{
				if ((this._PerSigaraK != value))
				{
					this.OnPerSigaraKChanging(value);
					this.SendPropertyChanging();
					this._PerSigaraK = value;
					this.SendPropertyChanged("PerSigaraK");
					this.OnPerSigaraKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerAskerlik", DbType="NVarChar(20)")]
		public string PerAskerlik
		{
			get
			{
				return this._PerAskerlik;
			}
			set
			{
				if ((this._PerAskerlik != value))
				{
					this.OnPerAskerlikChanging(value);
					this.SendPropertyChanging();
					this._PerAskerlik = value;
					this.SendPropertyChanged("PerAskerlik");
					this.OnPerAskerlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerIBAN", DbType="NVarChar(26)")]
		public string PerIBAN
		{
			get
			{
				return this._PerIBAN;
			}
			set
			{
				if ((this._PerIBAN != value))
				{
					this.OnPerIBANChanging(value);
					this.SendPropertyChanging();
					this._PerIBAN = value;
					this.SendPropertyChanged("PerIBAN");
					this.OnPerIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mesaiid", DbType="Int")]
		public System.Nullable<int> Mesaiid
		{
			get
			{
				return this._Mesaiid;
			}
			set
			{
				if ((this._Mesaiid != value))
				{
					this.OnMesaiidChanging(value);
					this.SendPropertyChanging();
					this._Mesaiid = value;
					this.SendPropertyChanged("Mesaiid");
					this.OnMesaiidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerIsTel", DbType="NVarChar(20)")]
		public string PerIsTel
		{
			get
			{
				return this._PerIsTel;
			}
			set
			{
				if ((this._PerIsTel != value))
				{
					this.OnPerIsTelChanging(value);
					this.SendPropertyChanging();
					this._PerIsTel = value;
					this.SendPropertyChanged("PerIsTel");
					this.OnPerIsTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerWpTel", DbType="NVarChar(20)")]
		public string PerWpTel
		{
			get
			{
				return this._PerWpTel;
			}
			set
			{
				if ((this._PerWpTel != value))
				{
					this.OnPerWpTelChanging(value);
					this.SendPropertyChanging();
					this._PerWpTel = value;
					this.SendPropertyChanged("PerWpTel");
					this.OnPerWpTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini1AdSoyad", DbType="NVarChar(70)")]
		public string Yakini1AdSoyad
		{
			get
			{
				return this._Yakini1AdSoyad;
			}
			set
			{
				if ((this._Yakini1AdSoyad != value))
				{
					this.OnYakini1AdSoyadChanging(value);
					this.SendPropertyChanging();
					this._Yakini1AdSoyad = value;
					this.SendPropertyChanged("Yakini1AdSoyad");
					this.OnYakini1AdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini1Tel", DbType="NVarChar(20)")]
		public string Yakini1Tel
		{
			get
			{
				return this._Yakini1Tel;
			}
			set
			{
				if ((this._Yakini1Tel != value))
				{
					this.OnYakini1TelChanging(value);
					this.SendPropertyChanging();
					this._Yakini1Tel = value;
					this.SendPropertyChanged("Yakini1Tel");
					this.OnYakini1TelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini1Derece", DbType="NVarChar(50)")]
		public string Yakini1Derece
		{
			get
			{
				return this._Yakini1Derece;
			}
			set
			{
				if ((this._Yakini1Derece != value))
				{
					this.OnYakini1DereceChanging(value);
					this.SendPropertyChanging();
					this._Yakini1Derece = value;
					this.SendPropertyChanged("Yakini1Derece");
					this.OnYakini1DereceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini2AdSoyad", DbType="NVarChar(70)")]
		public string Yakini2AdSoyad
		{
			get
			{
				return this._Yakini2AdSoyad;
			}
			set
			{
				if ((this._Yakini2AdSoyad != value))
				{
					this.OnYakini2AdSoyadChanging(value);
					this.SendPropertyChanging();
					this._Yakini2AdSoyad = value;
					this.SendPropertyChanged("Yakini2AdSoyad");
					this.OnYakini2AdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini2Tel", DbType="NVarChar(20)")]
		public string Yakini2Tel
		{
			get
			{
				return this._Yakini2Tel;
			}
			set
			{
				if ((this._Yakini2Tel != value))
				{
					this.OnYakini2TelChanging(value);
					this.SendPropertyChanging();
					this._Yakini2Tel = value;
					this.SendPropertyChanged("Yakini2Tel");
					this.OnYakini2TelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yakini2Derece", DbType="NVarChar(50)")]
		public string Yakini2Derece
		{
			get
			{
				return this._Yakini2Derece;
			}
			set
			{
				if ((this._Yakini2Derece != value))
				{
					this.OnYakini2DereceChanging(value);
					this.SendPropertyChanging();
					this._Yakini2Derece = value;
					this.SendPropertyChanged("Yakini2Derece");
					this.OnYakini2DereceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans1Ad", DbType="NVarChar(150)")]
		public string SertifikaLisans1Ad
		{
			get
			{
				return this._SertifikaLisans1Ad;
			}
			set
			{
				if ((this._SertifikaLisans1Ad != value))
				{
					this.OnSertifikaLisans1AdChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans1Ad = value;
					this.SendPropertyChanged("SertifikaLisans1Ad");
					this.OnSertifikaLisans1AdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans1VerenKurum", DbType="NVarChar(150)")]
		public string SertifikaLisans1VerenKurum
		{
			get
			{
				return this._SertifikaLisans1VerenKurum;
			}
			set
			{
				if ((this._SertifikaLisans1VerenKurum != value))
				{
					this.OnSertifikaLisans1VerenKurumChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans1VerenKurum = value;
					this.SendPropertyChanged("SertifikaLisans1VerenKurum");
					this.OnSertifikaLisans1VerenKurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans1Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SertifikaLisans1Tarihi
		{
			get
			{
				return this._SertifikaLisans1Tarihi;
			}
			set
			{
				if ((this._SertifikaLisans1Tarihi != value))
				{
					this.OnSertifikaLisans1TarihiChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans1Tarihi = value;
					this.SendPropertyChanged("SertifikaLisans1Tarihi");
					this.OnSertifikaLisans1TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans2Ad", DbType="NVarChar(150)")]
		public string SertifikaLisans2Ad
		{
			get
			{
				return this._SertifikaLisans2Ad;
			}
			set
			{
				if ((this._SertifikaLisans2Ad != value))
				{
					this.OnSertifikaLisans2AdChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans2Ad = value;
					this.SendPropertyChanged("SertifikaLisans2Ad");
					this.OnSertifikaLisans2AdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans2VerenKurum", DbType="NVarChar(150)")]
		public string SertifikaLisans2VerenKurum
		{
			get
			{
				return this._SertifikaLisans2VerenKurum;
			}
			set
			{
				if ((this._SertifikaLisans2VerenKurum != value))
				{
					this.OnSertifikaLisans2VerenKurumChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans2VerenKurum = value;
					this.SendPropertyChanged("SertifikaLisans2VerenKurum");
					this.OnSertifikaLisans2VerenKurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SertifikaLisans2Tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SertifikaLisans2Tarihi
		{
			get
			{
				return this._SertifikaLisans2Tarihi;
			}
			set
			{
				if ((this._SertifikaLisans2Tarihi != value))
				{
					this.OnSertifikaLisans2TarihiChanging(value);
					this.SendPropertyChanging();
					this._SertifikaLisans2Tarihi = value;
					this.SendPropertyChanged("SertifikaLisans2Tarihi");
					this.OnSertifikaLisans2TarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil1", DbType="NVarChar(50)")]
		public string YabanciDil1
		{
			get
			{
				return this._YabanciDil1;
			}
			set
			{
				if ((this._YabanciDil1 != value))
				{
					this.OnYabanciDil1Changing(value);
					this.SendPropertyChanging();
					this._YabanciDil1 = value;
					this.SendPropertyChanged("YabanciDil1");
					this.OnYabanciDil1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil1Düzey", DbType="NVarChar(50)")]
		public string YabanciDil1Düzey
		{
			get
			{
				return this._YabanciDil1Düzey;
			}
			set
			{
				if ((this._YabanciDil1Düzey != value))
				{
					this.OnYabanciDil1DüzeyChanging(value);
					this.SendPropertyChanging();
					this._YabanciDil1Düzey = value;
					this.SendPropertyChanged("YabanciDil1Düzey");
					this.OnYabanciDil1DüzeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil2", DbType="NVarChar(50)")]
		public string YabanciDil2
		{
			get
			{
				return this._YabanciDil2;
			}
			set
			{
				if ((this._YabanciDil2 != value))
				{
					this.OnYabanciDil2Changing(value);
					this.SendPropertyChanging();
					this._YabanciDil2 = value;
					this.SendPropertyChanged("YabanciDil2");
					this.OnYabanciDil2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil2Düzey", DbType="NVarChar(50)")]
		public string YabanciDil2Düzey
		{
			get
			{
				return this._YabanciDil2Düzey;
			}
			set
			{
				if ((this._YabanciDil2Düzey != value))
				{
					this.OnYabanciDil2DüzeyChanging(value);
					this.SendPropertyChanging();
					this._YabanciDil2Düzey = value;
					this.SendPropertyChanged("YabanciDil2Düzey");
					this.OnYabanciDil2DüzeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil3", DbType="NVarChar(50)")]
		public string YabanciDil3
		{
			get
			{
				return this._YabanciDil3;
			}
			set
			{
				if ((this._YabanciDil3 != value))
				{
					this.OnYabanciDil3Changing(value);
					this.SendPropertyChanging();
					this._YabanciDil3 = value;
					this.SendPropertyChanged("YabanciDil3");
					this.OnYabanciDil3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YabanciDil3Düzey", DbType="NVarChar(50)")]
		public string YabanciDil3Düzey
		{
			get
			{
				return this._YabanciDil3Düzey;
			}
			set
			{
				if ((this._YabanciDil3Düzey != value))
				{
					this.OnYabanciDil3DüzeyChanging(value);
					this.SendPropertyChanging();
					this._YabanciDil3Düzey = value;
					this.SendPropertyChanged("YabanciDil3Düzey");
					this.OnYabanciDil3DüzeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsYeri1", DbType="NVarChar(100)")]
		public string IsYeri1
		{
			get
			{
				return this._IsYeri1;
			}
			set
			{
				if ((this._IsYeri1 != value))
				{
					this.OnIsYeri1Changing(value);
					this.SendPropertyChanging();
					this._IsYeri1 = value;
					this.SendPropertyChanged("IsYeri1");
					this.OnIsYeri1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUnvan1", DbType="NVarChar(50)")]
		public string IsUnvan1
		{
			get
			{
				return this._IsUnvan1;
			}
			set
			{
				if ((this._IsUnvan1 != value))
				{
					this.OnIsUnvan1Changing(value);
					this.SendPropertyChanging();
					this._IsUnvan1 = value;
					this.SendPropertyChanged("IsUnvan1");
					this.OnIsUnvan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseGirisD1", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseGirisD1
		{
			get
			{
				return this._IseGirisD1;
			}
			set
			{
				if ((this._IseGirisD1 != value))
				{
					this.OnIseGirisD1Changing(value);
					this.SendPropertyChanging();
					this._IseGirisD1 = value;
					this.SendPropertyChanged("IseGirisD1");
					this.OnIseGirisD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenCikis1", DbType="DateTime")]
		public System.Nullable<System.DateTime> IstenCikis1
		{
			get
			{
				return this._IstenCikis1;
			}
			set
			{
				if ((this._IstenCikis1 != value))
				{
					this.OnIstenCikis1Changing(value);
					this.SendPropertyChanging();
					this._IstenCikis1 = value;
					this.SendPropertyChanged("IstenCikis1");
					this.OnIstenCikis1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenAyrilis1", DbType="NVarChar(100)")]
		public string IstenAyrilis1
		{
			get
			{
				return this._IstenAyrilis1;
			}
			set
			{
				if ((this._IstenAyrilis1 != value))
				{
					this.OnIstenAyrilis1Changing(value);
					this.SendPropertyChanging();
					this._IstenAyrilis1 = value;
					this.SendPropertyChanged("IstenAyrilis1");
					this.OnIstenAyrilis1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsYeri2", DbType="NVarChar(100)")]
		public string IsYeri2
		{
			get
			{
				return this._IsYeri2;
			}
			set
			{
				if ((this._IsYeri2 != value))
				{
					this.OnIsYeri2Changing(value);
					this.SendPropertyChanging();
					this._IsYeri2 = value;
					this.SendPropertyChanged("IsYeri2");
					this.OnIsYeri2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUnvan2", DbType="NVarChar(100)")]
		public string IsUnvan2
		{
			get
			{
				return this._IsUnvan2;
			}
			set
			{
				if ((this._IsUnvan2 != value))
				{
					this.OnIsUnvan2Changing(value);
					this.SendPropertyChanging();
					this._IsUnvan2 = value;
					this.SendPropertyChanged("IsUnvan2");
					this.OnIsUnvan2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseGirisD2", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseGirisD2
		{
			get
			{
				return this._IseGirisD2;
			}
			set
			{
				if ((this._IseGirisD2 != value))
				{
					this.OnIseGirisD2Changing(value);
					this.SendPropertyChanging();
					this._IseGirisD2 = value;
					this.SendPropertyChanged("IseGirisD2");
					this.OnIseGirisD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenCikis2", DbType="DateTime")]
		public System.Nullable<System.DateTime> IstenCikis2
		{
			get
			{
				return this._IstenCikis2;
			}
			set
			{
				if ((this._IstenCikis2 != value))
				{
					this.OnIstenCikis2Changing(value);
					this.SendPropertyChanging();
					this._IstenCikis2 = value;
					this.SendPropertyChanged("IstenCikis2");
					this.OnIstenCikis2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenAyrilis2", DbType="NVarChar(100)")]
		public string IstenAyrilis2
		{
			get
			{
				return this._IstenAyrilis2;
			}
			set
			{
				if ((this._IstenAyrilis2 != value))
				{
					this.OnIstenAyrilis2Changing(value);
					this.SendPropertyChanging();
					this._IstenAyrilis2 = value;
					this.SendPropertyChanged("IstenAyrilis2");
					this.OnIstenAyrilis2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsYeri3", DbType="NVarChar(100)")]
		public string IsYeri3
		{
			get
			{
				return this._IsYeri3;
			}
			set
			{
				if ((this._IsYeri3 != value))
				{
					this.OnIsYeri3Changing(value);
					this.SendPropertyChanging();
					this._IsYeri3 = value;
					this.SendPropertyChanged("IsYeri3");
					this.OnIsYeri3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUnvan3", DbType="NVarChar(100)")]
		public string IsUnvan3
		{
			get
			{
				return this._IsUnvan3;
			}
			set
			{
				if ((this._IsUnvan3 != value))
				{
					this.OnIsUnvan3Changing(value);
					this.SendPropertyChanging();
					this._IsUnvan3 = value;
					this.SendPropertyChanged("IsUnvan3");
					this.OnIsUnvan3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseGirisD3", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseGirisD3
		{
			get
			{
				return this._IseGirisD3;
			}
			set
			{
				if ((this._IseGirisD3 != value))
				{
					this.OnIseGirisD3Changing(value);
					this.SendPropertyChanging();
					this._IseGirisD3 = value;
					this.SendPropertyChanged("IseGirisD3");
					this.OnIseGirisD3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenCikis3", DbType="DateTime")]
		public System.Nullable<System.DateTime> IstenCikis3
		{
			get
			{
				return this._IstenCikis3;
			}
			set
			{
				if ((this._IstenCikis3 != value))
				{
					this.OnIstenCikis3Changing(value);
					this.SendPropertyChanging();
					this._IstenCikis3 = value;
					this.SendPropertyChanged("IstenCikis3");
					this.OnIstenCikis3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenAyrilis3", DbType="NVarChar(100)")]
		public string IstenAyrilis3
		{
			get
			{
				return this._IstenAyrilis3;
			}
			set
			{
				if ((this._IstenAyrilis3 != value))
				{
					this.OnIstenAyrilis3Changing(value);
					this.SendPropertyChanging();
					this._IstenAyrilis3 = value;
					this.SendPropertyChanged("IstenAyrilis3");
					this.OnIstenAyrilis3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsYeri4", DbType="NVarChar(100)")]
		public string IsYeri4
		{
			get
			{
				return this._IsYeri4;
			}
			set
			{
				if ((this._IsYeri4 != value))
				{
					this.OnIsYeri4Changing(value);
					this.SendPropertyChanging();
					this._IsYeri4 = value;
					this.SendPropertyChanged("IsYeri4");
					this.OnIsYeri4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUnvan4", DbType="NVarChar(100)")]
		public string IsUnvan4
		{
			get
			{
				return this._IsUnvan4;
			}
			set
			{
				if ((this._IsUnvan4 != value))
				{
					this.OnIsUnvan4Changing(value);
					this.SendPropertyChanging();
					this._IsUnvan4 = value;
					this.SendPropertyChanged("IsUnvan4");
					this.OnIsUnvan4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseGirisD4", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseGirisD4
		{
			get
			{
				return this._IseGirisD4;
			}
			set
			{
				if ((this._IseGirisD4 != value))
				{
					this.OnIseGirisD4Changing(value);
					this.SendPropertyChanging();
					this._IseGirisD4 = value;
					this.SendPropertyChanged("IseGirisD4");
					this.OnIseGirisD4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenCikis4", DbType="DateTime")]
		public System.Nullable<System.DateTime> IstenCikis4
		{
			get
			{
				return this._IstenCikis4;
			}
			set
			{
				if ((this._IstenCikis4 != value))
				{
					this.OnIstenCikis4Changing(value);
					this.SendPropertyChanging();
					this._IstenCikis4 = value;
					this.SendPropertyChanged("IstenCikis4");
					this.OnIstenCikis4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstenAyrilis4", DbType="NVarChar(100)")]
		public string IstenAyrilis4
		{
			get
			{
				return this._IstenAyrilis4;
			}
			set
			{
				if ((this._IstenAyrilis4 != value))
				{
					this.OnIstenAyrilis4Changing(value);
					this.SendPropertyChanging();
					this._IstenAyrilis4 = value;
					this.SendPropertyChanged("IstenAyrilis4");
					this.OnIstenAyrilis4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="Int")]
		public System.Nullable<int> Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departmans_Personnels", Storage="_Departmans", ThisKey="Departmanid", OtherKey="id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Departmans Departmans
		{
			get
			{
				return this._Departmans.Entity;
			}
			set
			{
				Departmans previousValue = this._Departmans.Entity;
				if (((previousValue != value) 
							|| (this._Departmans.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departmans.Entity = null;
						previousValue.Personnels.Remove(this);
					}
					this._Departmans.Entity = value;
					if ((value != null))
					{
						value.Personnels.Add(this);
						this._Departmanid = value.id;
					}
					else
					{
						this._Departmanid = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departmans");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departmans")]
	public partial class Departmans : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _DepAdi;
		
		private string _DepRolu;
		
		private System.Nullable<int> _Status;
		
		private EntitySet<Personnels> _Personnels;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDepAdiChanging(string value);
    partial void OnDepAdiChanged();
    partial void OnDepRoluChanging(string value);
    partial void OnDepRoluChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    #endregion
		
		public Departmans()
		{
			this._Personnels = new EntitySet<Personnels>(new Action<Personnels>(this.attach_Personnels), new Action<Personnels>(this.detach_Personnels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DepAdi
		{
			get
			{
				return this._DepAdi;
			}
			set
			{
				if ((this._DepAdi != value))
				{
					this.OnDepAdiChanging(value);
					this.SendPropertyChanging();
					this._DepAdi = value;
					this.SendPropertyChanged("DepAdi");
					this.OnDepAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepRolu", DbType="NVarChar(50)")]
		public string DepRolu
		{
			get
			{
				return this._DepRolu;
			}
			set
			{
				if ((this._DepRolu != value))
				{
					this.OnDepRoluChanging(value);
					this.SendPropertyChanging();
					this._DepRolu = value;
					this.SendPropertyChanged("DepRolu");
					this.OnDepRoluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departmans_Personnels", Storage="_Personnels", ThisKey="id", OtherKey="Departmanid")]
		public EntitySet<Personnels> Personnels
		{
			get
			{
				return this._Personnels;
			}
			set
			{
				this._Personnels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personnels(Personnels entity)
		{
			this.SendPropertyChanging();
			entity.Departmans = this;
		}
		
		private void detach_Personnels(Personnels entity)
		{
			this.SendPropertyChanging();
			entity.Departmans = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Izin")]
	public partial class Izin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _izinid;
		
		private int _KullaniciID;
		
		private int _Personnelid;
		
		private string _IzinTuru;
		
		private System.DateTime _IzinBaslangic;
		
		private System.DateTime _IzinBitis;
		
		private string _Islem;
		
		private string _Aciklama;
		
		private System.DateTime _Tarih;
		
		private System.DateTime _Saat;
		
		private System.Nullable<int> _DonemAy;
		
		private System.Nullable<int> _DonemYil;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnizinidChanging(int value);
    partial void OnizinidChanged();
    partial void OnKullaniciIDChanging(int value);
    partial void OnKullaniciIDChanged();
    partial void OnPersonnelidChanging(int value);
    partial void OnPersonnelidChanged();
    partial void OnIzinTuruChanging(string value);
    partial void OnIzinTuruChanged();
    partial void OnIzinBaslangicChanging(System.DateTime value);
    partial void OnIzinBaslangicChanged();
    partial void OnIzinBitisChanging(System.DateTime value);
    partial void OnIzinBitisChanged();
    partial void OnIslemChanging(string value);
    partial void OnIslemChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    partial void OnSaatChanging(System.DateTime value);
    partial void OnSaatChanged();
    partial void OnDonemAyChanging(System.Nullable<int> value);
    partial void OnDonemAyChanged();
    partial void OnDonemYilChanging(System.Nullable<int> value);
    partial void OnDonemYilChanged();
    #endregion
		
		public Izin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_izinid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int izinid
		{
			get
			{
				return this._izinid;
			}
			set
			{
				if ((this._izinid != value))
				{
					this.OnizinidChanging(value);
					this.SendPropertyChanging();
					this._izinid = value;
					this.SendPropertyChanged("izinid");
					this.OnizinidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciID", DbType="Int NOT NULL")]
		public int KullaniciID
		{
			get
			{
				return this._KullaniciID;
			}
			set
			{
				if ((this._KullaniciID != value))
				{
					this.OnKullaniciIDChanging(value);
					this.SendPropertyChanging();
					this._KullaniciID = value;
					this.SendPropertyChanged("KullaniciID");
					this.OnKullaniciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Personnelid", DbType="Int NOT NULL")]
		public int Personnelid
		{
			get
			{
				return this._Personnelid;
			}
			set
			{
				if ((this._Personnelid != value))
				{
					this.OnPersonnelidChanging(value);
					this.SendPropertyChanging();
					this._Personnelid = value;
					this.SendPropertyChanged("Personnelid");
					this.OnPersonnelidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinTuru", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string IzinTuru
		{
			get
			{
				return this._IzinTuru;
			}
			set
			{
				if ((this._IzinTuru != value))
				{
					this.OnIzinTuruChanging(value);
					this.SendPropertyChanging();
					this._IzinTuru = value;
					this.SendPropertyChanged("IzinTuru");
					this.OnIzinTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBaslangic", DbType="Date NOT NULL")]
		public System.DateTime IzinBaslangic
		{
			get
			{
				return this._IzinBaslangic;
			}
			set
			{
				if ((this._IzinBaslangic != value))
				{
					this.OnIzinBaslangicChanging(value);
					this.SendPropertyChanging();
					this._IzinBaslangic = value;
					this.SendPropertyChanged("IzinBaslangic");
					this.OnIzinBaslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBitis", DbType="Date NOT NULL")]
		public System.DateTime IzinBitis
		{
			get
			{
				return this._IzinBitis;
			}
			set
			{
				if ((this._IzinBitis != value))
				{
					this.OnIzinBitisChanging(value);
					this.SendPropertyChanging();
					this._IzinBitis = value;
					this.SendPropertyChanged("IzinBitis");
					this.OnIzinBitisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Islem", DbType="NVarChar(550) NOT NULL", CanBeNull=false)]
		public string Islem
		{
			get
			{
				return this._Islem;
			}
			set
			{
				if ((this._Islem != value))
				{
					this.OnIslemChanging(value);
					this.SendPropertyChanging();
					this._Islem = value;
					this.SendPropertyChanged("Islem");
					this.OnIslemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(850) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saat", DbType="DateTime NOT NULL")]
		public System.DateTime Saat
		{
			get
			{
				return this._Saat;
			}
			set
			{
				if ((this._Saat != value))
				{
					this.OnSaatChanging(value);
					this.SendPropertyChanging();
					this._Saat = value;
					this.SendPropertyChanged("Saat");
					this.OnSaatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonemAy", DbType="Int")]
		public System.Nullable<int> DonemAy
		{
			get
			{
				return this._DonemAy;
			}
			set
			{
				if ((this._DonemAy != value))
				{
					this.OnDonemAyChanging(value);
					this.SendPropertyChanging();
					this._DonemAy = value;
					this.SendPropertyChanged("DonemAy");
					this.OnDonemAyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonemYil", DbType="Int")]
		public System.Nullable<int> DonemYil
		{
			get
			{
				return this._DonemYil;
			}
			set
			{
				if ((this._DonemYil != value))
				{
					this.OnDonemYilChanging(value);
					this.SendPropertyChanging();
					this._DonemYil = value;
					this.SendPropertyChanged("DonemYil");
					this.OnDonemYilChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calendar")]
	public partial class Calendar
	{
		
		private System.DateTime _date;
		
		private string _event;
		
		public Calendar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="event", Storage="_event", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string @event
		{
			get
			{
				return this._event;
			}
			set
			{
				if ((this._event != value))
				{
					this._event = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
